### ISSUE TITLE
Error : Não há numeros  para enviar mensagens 

### ISSUE THREAD

**Issue by vbnetgenius** [paulowiz/envioMensagensWhatsAppProject#1]
Hi, I installed your program, but when I enter the numbers, this message is displayed, what is the reason for the problem? Does it only work with the numbers of a particular country?

![Screenshot_2](https://user-images.githubusercontent.com/8804113/82798899-6f6a3f00-9e8e-11ea-8eff-0929c9b1c7da.jpg)

**Comment by vbnetgenius** [comment]
Another issue : 
My phone number : 09339980400 but the send url is below : 
https://web.whatsapp.com/send?phone=550939980400&source=&data=#

**Comment by paulowiz** [comment]
It's true bro, I will update in the interface to accept other countries =)

**Comment by paulowiz** [comment]
Hello everyone,

I've fixed the problem and update somethings...
- After WhatsApp Web send all messages my service create a logfile.txt as this log-31052020-030739.txt
-Include the field Country Code
- You can send a big message right now
- The set interval between messages ( With the error of number or not ) in 15 seconds
- Some messages in English added

Can you test this feature?

Banche: https://github.com/paulowiz/envioMensagensWhatsAppProject/tree/feature/countryCode
![whatsappSender](https://user-images.githubusercontent.com/18649504/83346392-47496880-a2f2-11ea-8ab3-e5fce84f75e6.gif)
